name: Build and Release ChestLogger

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          # Get the latest tag
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag: $LATEST_TAG"
          # If no tags are found, start with v1.0.0
          if [ -z "$LATEST_TAG" ]; then
            NEW_TAG="v1.0.0"
          else
            # Increment the version number
            NEW_TAG=$(echo $LATEST_TAG | awk -F. -v OFS=. '{$NF += 1 ; print}')
          fi
          echo "New tag: $NEW_TAG"
          echo "::set-output name=new_tag::$NEW_TAG"

      - name: Create Tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag ${{ steps.get_latest_tag.outputs.new_tag }}
          git push origin ${{ steps.get_latest_tag.outputs.new_tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/ChestLogger.jar
          tag_name: ${{ steps.get_latest_tag.outputs.new_tag }}
          name: Release ${{ steps.get_latest_tag.outputs.new_tag }}
          body: |
            ## Changes in this release
            - Add your changelog or release notes here.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
