# Workflow to build the Java project and create a release on GitHub

name: Java CI and Release

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ChestLogger
          path: target/ChestLogger.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: ChestLogger

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ChestLogger.jar
          tag: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## Changes in this release
            - Add your changelog or release notes here.
          draft: false
          prerelease: false
